/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice9;

import org.testng.Assert;
import org.testng.annotations.Test;
import practice9.app.src.main.java.practice9.App;


public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        Assert.assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
