/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.main.java.practice9;

public class App {
    public String getGreeting() {
        return "Hello, I'm testing application!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
